#Student Name:
#Student ID:

#Student Name:
#Student ID:

#Student Name:
#Student ID:

#Student Name:
#Student ID:

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
# Following code is from https://github.com/amclean3695/Communities-and-Crime/blob/master/Communities_and_Crime.ipynb
# TODO : See is there any other means for pulling column names from C45 file format
#Reads in names from textfile and performs regex to extract the attribute names 
textfile = open('communities.names','r')
filetext = textfile.read()
textfile.close()
matches = re.findall(r'-{2}\s(\w+)\:{1}', filetext)
col_names = matches[2:] #corresponds to the 128 attributes

In [3]:
df = pd.read_csv('communities.data', header=None, names=col_names)

#data_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data'
#df = pd.read_csv(data_url, header=None)
# The above code does not work as PythonAnywhere blocks outgoing connections for free accounts to non-whitelisted sites

#print(df.head(5))
#dir(df)
print(df.shape)
#print(df['ViolentCrimesPerPop'].value_counts())

(1994, 128)


### Remove Non-Predictive Attributes

Of the 128 attributes loaded, for this dataset it is stated that:

Attribute Information: (122 predictive, 5 non-predictive, 1 goal) 
* state: US state (by number) - not counted as predictive above, but if considered, should be consided nominal (nominal) 
* county: numeric code for county - not predictive, and many missing values (numeric) 
* community: numeric code for community - not predictive and many missing values (numeric) 
* communityname: community name - not predictive - for information only (string) 
* fold: fold number for non-random 10 fold cross validation, potentially useful for debugging, paired tests - not predictive (numeric) 

Therefore, the first five columns shall be removed from the dataset

In [4]:
df = df.drop(['state', 'county', 'community', 'communityname', 'fold'], axis=1)
print(df.shape)


(1994, 123)


In [5]:
#print(df.head(5))
# From DePy_Talk Noteboook
# How much of your data is missing?
df.isnull().sum().sort_values(ascending=False).head()

ViolentCrimesPerPop    0
PctNotHSGrad           0
PctUnemployed          0
PctEmploy              0
PctEmplManu            0
dtype: int64

There are no cells with missing data
However, visually inspecting the data, there are cells with "?" and this needs to be replaced with "NaN" (Not a Number)

In [6]:
df = df.replace('?', np.nan)
print(df.columns[df.isnull().any()])

Index(['OtherPerCap', 'LemasSwornFT', 'LemasSwFTPerPop', 'LemasSwFTFieldOps',
       'LemasSwFTFieldPerPop', 'LemasTotalReq', 'LemasTotReqPerPop',
       'PolicReqPerOffic', 'PolicPerPop', 'RacialMatchCommPol',
       'PctPolicWhite', 'PctPolicBlack', 'PctPolicHisp', 'PctPolicAsian',
       'PctPolicMinor', 'OfficAssgnDrugUnits', 'NumKindsDrugsSeiz',
       'PolicAveOTWorked', 'PolicCars', 'PolicOperBudg', 'LemasPctPolicOnPatr',
       'LemasGangUnitDeploy', 'PolicBudgPerPop'],
      dtype='object')


In [7]:
df.isnull().sum().sort_values(ascending=False).head(25)

LemasSwFTFieldPerPop    1675
PctPolicAsian           1675
PolicBudgPerPop         1675
LemasSwornFT            1675
LemasSwFTPerPop         1675
LemasSwFTFieldOps       1675
LemasTotalReq           1675
LemasTotReqPerPop       1675
PolicReqPerOffic        1675
PolicPerPop             1675
RacialMatchCommPol      1675
PctPolicBlack           1675
PctPolicHisp            1675
PctPolicWhite           1675
PctPolicMinor           1675
PolicCars               1675
LemasGangUnitDeploy     1675
LemasPctPolicOnPatr     1675
OfficAssgnDrugUnits     1675
PolicOperBudg           1675
PolicAveOTWorked        1675
NumKindsDrugsSeiz       1675
OtherPerCap                1
PctLess9thGrade            0
PctPopUnderPov             0
dtype: int64

In [8]:
#print(df.isnull().sum())
print(df.shape)
print(df.shape[0])
print(df['LemasSwFTFieldPerPop'].isnull().sum())
for column in df:
    if(df[column].isnull().sum()>=(df.shape[0]/2)):
        print("Column ", column, df[column].isnull().sum())
        df = df.drop([column], axis=1)
print(df.shape)

(1994, 123)
1994
1675
Column  LemasSwornFT 1675
Column  LemasSwFTPerPop 1675
Column  LemasSwFTFieldOps 1675
Column  LemasSwFTFieldPerPop 1675
Column  LemasTotalReq 1675
Column  LemasTotReqPerPop 1675
Column  PolicReqPerOffic 1675
Column  PolicPerPop 1675
Column  RacialMatchCommPol 1675
Column  PctPolicWhite 1675
Column  PctPolicBlack 1675
Column  PctPolicHisp 1675
Column  PctPolicAsian 1675
Column  PctPolicMinor 1675
Column  OfficAssgnDrugUnits 1675
Column  NumKindsDrugsSeiz 1675
Column  PolicAveOTWorked 1675
Column  PolicCars 1675
Column  PolicOperBudg 1675
Column  LemasPctPolicOnPatr 1675
Column  LemasGangUnitDeploy 1675
Column  PolicBudgPerPop 1675
(1994, 101)


In [9]:
df.isnull().sum().sort_values(ascending=False).head(25)

OtherPerCap            1
PctOccupManu           0
HispPerCap             0
NumUnderPov            0
PctPopUnderPov         0
PctLess9thGrade        0
PctNotHSGrad           0
PctBSorMore            0
PctUnemployed          0
PctEmploy              0
PctEmplManu            0
PctEmplProfServ        0
ViolentCrimesPerPop    0
NumIlleg               0
MalePctDivorce         0
MalePctNevMarr         0
FemalePctDiv           0
TotalPctDiv            0
PersPerFam             0
PctFam2Par             0
PctKids2Par            0
PctYoungKids2Par       0
PctTeen2Par            0
PctWorkMomYoungKids    0
PctOccupMgmtProf       0
dtype: int64

There is only one missing value remaining but lets impute it for the craic using code from the DePy_Talk notebook

In [10]:
# print(df['OtherPerCap'][130])

# # dir(sklearn)
# # from sklearn.impute import SimpleImputer

# # imp = SimpleImputer(missing_values=np.nan, strategy='mean')
# # imp.fit(df) 
# # X = pd.DataFrame(data=imp.transform(df) , columns=df.columns)

# from sklearn.impute import SimpleImputer
# my_imputer = SimpleImputer()

#TEMP WORKAROUND
# Set to median
print(df['OtherPerCap'][130])
#print(df['OtherPerCap'].median())
#print(df['OtherPerCap'].mean())
dir(df['OtherPerCap'])
miss_median = df['OtherPerCap'].median()
df['OtherPerCap'][130] = miss_median
print(df['OtherPerCap'][130])

nan
0.25


/usr/lib/python3.6/site-packages/IPython/kernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


### Outlier Detection

In [11]:
# From DePy_Talk Notebook
# def find_outliers_tukey(x):
#     q1 = np.percentile(x, 25)
#     q3 = np.percentile(x, 75)
#     iqr = q3-q1
#     floor = q1 - 1.5*iqr
#     ceiling = q3 + 1.5*iqr
#     outlier_indices = list(x.index[(x < floor)|(x > ceiling)])
#     outlier_values = list(x[outlier_indices])
    
#     return outlier_indices, outlier_values

# tukey_indices, tukey_values = find_outliers_tukey(df['ViolentCrimesPerPop'])

# print("Shape Before Outlier Removal")
# print(df.shape)
# print("Entry 26", df['ViolentCrimesPerPop'][26])
# print("Outliers = ",len(tukey_indices), "out of ",len(df['ViolentCrimesPerPop']))
# print(np.sort(tukey_values))
# print(np.sort(tukey_indices))
# for i in range(len(tukey_indices)):
#     print("i : ", i, "Index", tukey_indices[i], "Value", tukey_values[i])
#     # Drop row containing the outlier
#     df = df.drop([tukey_indices[i]], axis=0)
# print("Shape After Outlier Removal")
# print(df.shape)


Shape Before Outlier Removal
(1994, 101)
Entry 26 0.84
Outliers =  110 out of  1994
[0.73 0.73 0.73 0.74 0.74 0.74 0.75 0.75 0.75 0.75 0.75 0.76 0.76 0.76
 0.76 0.77 0.78 0.78 0.79 0.79 0.8  0.8  0.8  0.81 0.81 0.81 0.81 0.81
 0.82 0.82 0.82 0.82 0.83 0.83 0.83 0.83 0.84 0.84 0.85 0.85 0.85 0.86
 0.86 0.86 0.86 0.86 0.87 0.87 0.87 0.87 0.88 0.88 0.89 0.9  0.9  0.9
 0.91 0.91 0.93 0.93 0.94 0.95 0.95 0.96 0.97 0.97 1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]
[  26   42   79   82  116  146  149  151  154  157  174  177  226  233
  248  250  255  333  362  375  399  400  410  413  420  427  447  457
  462  472  499  539  545  560  564  591  600  615  630  631  641  667
  669  675  676  678  723  726  776  810  828  836  841  858  866  867
  909  952  953  955  957  976  998 1001 1025 1041 1044 1056 1119 1134
 1154 115

In [12]:
print(df['ViolentCrimesPerPop'])

0       0.20
1       0.67
2       0.43
3       0.12
4       0.03
5       0.14
6       0.03
7       0.55
8       0.53
9       0.15
10      0.24
11      0.08
12      0.06
13      0.09
14      0.21
15      0.30
16      0.49
17      0.07
18      0.15
19      0.03
20      0.34
21      0.69
22      0.21
23      0.63
24      0.31
25      0.12
27      0.10
28      0.49
29      0.02
30      0.16
        ... 
1963    0.45
1964    0.60
1965    0.69
1966    0.30
1967    0.04
1968    0.19
1970    0.53
1971    0.22
1972    0.30
1973    0.04
1974    0.52
1975    0.09
1976    0.08
1977    0.25
1978    0.04
1979    0.16
1980    0.28
1981    0.07
1982    0.03
1983    0.56
1984    0.14
1985    0.14
1986    0.02
1987    0.04
1988    0.19
1989    0.09
1990    0.45
1991    0.23
1992    0.19
1993    0.48
Name: ViolentCrimesPerPop, Length: 1884, dtype: float64


### Split Up Dataset

In [13]:
print(df.shape)
print(df.head())
dataset = df.values
print(dataset.shape)
X = dataset[:, 0:100]
y = dataset[:, 100]
print(X[0])
#X = df[:,0:100].values
#y = df[:,100].values

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1) 

(1884, 101)
   population  householdsize  racepctblack  racePctWhite  racePctAsian  \
0        0.19           0.33          0.02          0.90          0.12   
1        0.00           0.16          0.12          0.74          0.45   
2        0.00           0.42          0.49          0.56          0.17   
3        0.04           0.77          1.00          0.08          0.12   
4        0.01           0.55          0.02          0.95          0.09   

   racePctHisp  agePct12t21  agePct12t29  agePct16t24  agePct65up  \
0         0.17         0.34         0.47         0.29        0.32   
1         0.07         0.26         0.59         0.35        0.27   
2         0.04         0.39         0.47         0.28        0.32   
3         0.10         0.51         0.50         0.34        0.21   
4         0.05         0.38         0.38         0.23        0.36   

          ...           PctForeignBorn  PctBornSameState  PctSameHouse85  \
0         ...                     0.12              

In [14]:
# Scale the dataset
from sklearn.preprocessing import StandardScaler 
# Scale the data with respect to the training data set 
scaler = StandardScaler() 
scaler.fit(X_train) 

X_scaled_train = scaler.transform(X_train) 
# Scaling the test set using the transform defined by the train set. 
X_scaled_test = scaler.transform(X_test) 

/home/ul9939245/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ul9939245/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ul9939245/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [15]:
print(X_scaled_train.shape)
print(X_scaled_test.shape)

(1507, 100)
(377, 100)


In [16]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(X_scaled_train, y_train)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [17]:
print(clf.coef_)
print(clf.intercept_)

[ 0.          0.          0.         -0.          0.          0.
  0.          0.          0.          0.          0.          0.
 -0.         -0.         -0.         -0.          0.          0.
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.          0.          0.          0.
  0.         -0.          0.         -0.         -0.         -0.
  0.         -0.          0.          0.          0.          0.
  0.         -0.         -0.02035968 -0.         -0.         -0.
 -0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
 -0.          0.          0.          0.          0.         -0.
  0.         -0.          0.          0.         -0.          0.
 -0.         -0.          0.         -0.         -0.          0.
  0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.          0.          0.         -0.          0.
  0.          0.         

In [18]:
y_hat = clf.predict(X_scaled_test)

In [19]:
print(y_hat.shape)
print(y_test.shape)
print(y_hat[0:5])
print(y_test[0:5])
print(clf.score(X_scaled_test,y_test))

(377,)
(377,)
[0.16555333 0.20292006 0.20292006 0.16875619 0.20185244]
[0.05 0.28 0.16 0.04 0.24]
0.14076042961651192


In [20]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_test, y_hat)
print(y_hat[0:20])
print(y_test[0:20])

[0.16555333 0.20292006 0.20292006 0.16875619 0.20185244 0.20825817
 0.21146103 0.22747534 0.17836478 0.19224385 0.18050002 0.19437909
 0.19651434 0.1794324  0.18583813 0.19010861 0.19437909 0.22427248
 0.18583813 0.21146103]
[0.05 0.28 0.16 0.04 0.24 0.21 0.4 0.36 0.04 0.03 0.14 0.19 0.16 0.13 0.18
 0.36 0.05 0.52 0.02 0.09]


In [21]:
from sklearn.metrics import mean_absolute_error
print("MAE ", mean_absolute_error(y_test, y_hat))
from sklearn.metrics import mean_squared_error
print("MSE ", mean_squared_error(y_test, y_hat))
from sklearn.metrics import r2_score
print("R2S ", r2_score(y_test, y_hat))

MAE  0.12368584519753385
MSE  0.02429427052208181
R2S  0.14076042961651192


### Gridsearch

In [22]:
from sklearn.linear_model import LassoCV
lasso_cv = LassoCV(alphas = None, cv = 10, max_iter = 100000, random_state=1) 
lasso_cv.fit(X_scaled_train, y_train)
print(lasso_cv.alpha_)
#print(lasso_cv.mse_path_)
#print(lasso_cv.alphas_)


0.001483850379105968


In [23]:
y_hat_cv = lasso_cv.predict(X_scaled_test)
print(y_hat_cv[0:20])
print(y_test[0:20])
print("MAE ", mean_absolute_error(y_test, y_hat_cv))
print("MSE ", mean_squared_error(y_test, y_hat_cv))
print("R2S ", r2_score(y_test, y_hat_cv))

[-0.00344722  0.18839076  0.26879589  0.01994383  0.13933228  0.26733997
  0.40733025  0.32498373  0.09279517  0.11048849  0.07885754  0.15683005
  0.16033197  0.0534839   0.11631749  0.19311162  0.1884257   0.33834337
  0.0445184   0.20456927]
[0.05 0.28 0.16 0.04 0.24 0.21 0.4 0.36 0.04 0.03 0.14 0.19 0.16 0.13 0.18
 0.36 0.05 0.52 0.02 0.09]
MAE  0.08354865135259368
MSE  0.012934545858282779
R2S  0.542531082945064


### PCA

In [24]:
from sklearn.decomposition import PCA 
pca = PCA()
pca.fit(X_scaled_train)
X_pca_train = pca.transform(X_scaled_train)
print(pca.explained_variance_)
print(len(pca.explained_variance_))
print(X_pca_train.shape)
print(type(pca.explained_variance_))
print(pca.explained_variance_.sum())
print(pca.explained_variance_ratio_)

n_components_pca = 0

percent_contrib = 0.05

for i in range(len(pca.explained_variance_)):
    if(pca.explained_variance_ratio_[i]>=(percent_contrib/100)):
        n_components_pca+=1
print("Number of PCA components that contribute >=",percent_contrib,"% of variance is ",n_components_pca)

pca_red = PCA(n_components=n_components_pca)
pca_red.fit(X_scaled_train)
X_pca_red_train = pca_red.transform(X_scaled_train)
X_pca_red_test = pca_red.transform(X_scaled_test)
print(pca_red.explained_variance_)
print(len(pca_red.explained_variance_))
print(X_pca_red_train.shape)
print(X_pca_red_test.shape)
print(type(pca_red.explained_variance_))
print(pca_red.explained_variance_.sum())
print(pca_red.explained_variance_ratio_)
    

[2.53389904e+01 1.60551651e+01 9.24224043e+00 7.30850845e+00
 5.86393001e+00 4.22326901e+00 3.21383004e+00 2.89620146e+00
 2.12491830e+00 1.66292526e+00 1.55366828e+00 1.48991928e+00
 1.37254275e+00 1.04538337e+00 9.27806043e-01 8.83034793e-01
 8.18951642e-01 7.84032396e-01 7.19236995e-01 6.66352892e-01
 6.46130918e-01 6.25133887e-01 5.93365637e-01 5.43366469e-01
 5.21728839e-01 4.88606794e-01 4.61405244e-01 4.43865970e-01
 4.05327549e-01 3.94410166e-01 3.74987215e-01 3.68567782e-01
 3.53505050e-01 3.36881432e-01 3.07633097e-01 2.88994698e-01
 2.80964444e-01 2.72948857e-01 2.55307389e-01 2.42632742e-01
 2.30318112e-01 2.16740752e-01 2.10053349e-01 2.01961694e-01
 1.91819191e-01 1.81033854e-01 1.64798877e-01 1.48340854e-01
 1.45273163e-01 1.33252917e-01 1.19058471e-01 1.12044374e-01
 1.09630631e-01 1.03594007e-01 9.75739528e-02 8.48152087e-02
 7.73580547e-02 7.68028576e-02 7.23928938e-02 6.83373205e-02
 6.67382818e-02 6.23017993e-02 5.92601904e-02 5.43128252e-02
 4.90009179e-02 4.650017

In [25]:
clf_pca = linear_model.Lasso(alpha=0.1)
clf_pca.fit(X_pca_red_train, y_train)
y_pca_red_hat = clf_pca.predict(X_pca_red_test)
print(y_pca_red_hat.shape)
print(y_test.shape)
print(y_pca_red_hat[0:5])
print(y_test[0:5])
print(clf_pca.score(X_pca_red_test,y_test))
print("MAE ", mean_absolute_error(y_test, y_pca_red_hat))
from sklearn.metrics import mean_squared_error
print("MSE ", mean_squared_error(y_test, y_pca_red_hat))
from sklearn.metrics import r2_score
print("R2S ", r2_score(y_test, y_pca_red_hat))

(377,)
(377,)
[0.0036658  0.22523213 0.21224566 0.05761379 0.21700188]
[0.05 0.28 0.16 0.04 0.24]
0.3729715158239061
MAE  0.1027523676695448
MSE  0.01772869889223814
R2S  0.3729715158239061


In [26]:
lasso_pca_cv = LassoCV(alphas = None, cv = 10, max_iter = 1000, random_state=1) 
lasso_pca_cv.fit(X_pca_red_train, y_train)
print(lasso_pca_cv.alpha_)

y_pca_red_hat_cv = lasso_pca_cv.predict(X_pca_red_test)
print(y_pca_red_hat_cv[0:20])
print(y_test[0:20])
print("MAE ", mean_absolute_error(y_test, y_pca_red_hat_cv))
print("MSE ", mean_squared_error(y_test, y_pca_red_hat_cv))
print("R2S ", r2_score(y_test, y_pca_red_hat_cv))

0.0013049985089977575
[0.0043172  0.19591229 0.26606527 0.03638738 0.15470177 0.28571754
 0.40831817 0.31874816 0.10278159 0.10788911 0.08113232 0.16930392
 0.16354255 0.04327862 0.12340291 0.21171587 0.18266532 0.33689096
 0.04300176 0.2034089 ]
[0.05 0.28 0.16 0.04 0.24 0.21 0.4 0.36 0.04 0.03 0.14 0.19 0.16 0.13 0.18
 0.36 0.05 0.52 0.02 0.09]
MAE  0.08393899863963541
MSE  0.013011750901331757
R2S  0.5398004955845361
